### ISSUE TITLE
1x1 Bug

### ISSUE THREAD

**Issue by Zodsmar** [Zodsmar/SeedSearcherStandaloneTool#15]
I've had success finding common biomes such as "Plains" in a 10x10 search, but when setting it for Mooshroom Island (Now known as Mooshroom Fields) on a 1x1 - this ran for over 4 hours, combed over 8 million, and didn't find anything.

I'm curious if the 1x1 area is a bug as trying this with a 10x10 area produces results. (All within a matter of seconds)

**Comment by ThePlayingGoblin** [comment]
The lower your radius, the lower the chance of finding the biome you want. I just leave it by the default 512x512 blocks.

**Comment by RedSparr0w** [comment]
I think this may be because the game doesn't allow you to spawn on mushroom fields biome IIRC.
But you can spawn nearby.

**Comment by Caleb-JC-Hussey** [comment]
The program seems to search from (0,0) though. Not spawn. It should be able to find one eventually. It crashes after a half hour on my machine though. 🙃

**Comment by RedSparr0w** [comment]
It checks biomes from spawn and only 0,0 if no spawn found IIRC.

**Comment by Caleb-JC-Hussey** [comment]
> It checks biomes from spawn and only 0,0 if no spawn found IIRC.

OH! That makes more sense! XD Sorry. I haven't actually looked into the code. I just figured that out after using it a few times in 1*1 with it leading me to (0, 0). (For mushroom fields)

I also wasn't able to replicate the issue this morning. I think I'll have to let it run overnight tonight. (The issue was something about a domain or overflow exception. Something having to do with some value being the wrong size. My memory is a bit fuzzy. I don't code Java, so I'm kinda confused with the way it displays errors. Definitely not as easy as Python! 😅)

**Comment by Zodsmar** [comment]
Fixed the 1x1 search radius bug. Will be working in the next version! Closed for now
