### ISSUE TITLE
Searching seeds are really slow

### ISSUE THREAD

**Issue by Killstepz** [Zodsmar/SeedSearcherStandaloneTool#25]
Hey there, iv used your program in the past and i really love it, the options you have are very nice. before the 1.15.2 update, it feels so much slower to search for seeds, im a big seed hunter myself and i have tons of reddit posts about sick seeds iv found .but i actually use a self made program atm. wich also searches for seeds and it searches as fast as light can trival :P, here is a link to the tool i use atm : https://mega.nz/#!3NUEzCia!xGk-EwMGrIL372_SPsRVN-0Zp7vUttMEOAJlPQGLhnc
i tought id share this maybe it intrests you, but i would prefer to use your program ofc. <3 thx

**Comment by Zodsmar** [comment]
The program is interesting. Do you have the code behind how it is searching? The fact that it is searching so fast makes me think its a different approach. Would love to see what approach is being taken and maybe I can work a bit of that approach into the seed searcher

**Comment by TelepathicGrunt** [comment]
I am the maker of that program and it's fairly simple what I did. The first thing the program does is opens many threads and has each of them search through a different seed simultaneously to fully utilize the CPU. 

The second thing I did was I only check every 50 blocks instead of every single block. This way, it speeds up the search like crazy without much loss in accuracy since the majority of biomes are much larger than 50 blocks. It also makes finding combos easier since I only need to check at 50 blocks and 100 blocks to west and south of a targeted biome for the other biome wanted for the combo without needing to worry about river borders. 

Then for structure/biome combos, the trick to this one is search for the structure first as structure finding is insanely faster than biome searching. Then once you find a structure, then check around it for the targeted biome wanted for the structure/biome combo.

Just small tricks and shortcuts like this makes biome finding much, much faster. Though since 1.16 is going to have a /locatebiome command that is surprisingly fast, they probably made the biome gen faster or have an even better way of finding biomes. You should check that out too when 1.16 comes out and see if you can incorporate how the /locatebiome command works into your program!

**Comment by Zodsmar** [comment]
How are you determining the biome size. Or are you just actually searching every 50 blocks cause in that case yeah that would speed it up but it's not 100% perfect. I will take a look and dig into this more. Need to look into the threading. If you want to fork the code and try to modify mine and do a pull request I am always looking for help. You seem to understand this a lot. My goal is to make the tool accessible to everyone and the more help the faster I can develop the tool! Thanks this is amazing feedback!

**Comment by TelepathicGrunt** [comment]
It's every 50 blocks regardless of biome size. Though if you are trying to support stuff like large biome worldtype, then you can increase/decrease the step to help keep the search consistent across worldtypes. But at the very least, giving people the option to change the distance between steps can let people decide how much accuracy they want VS speed. :)

 As for multithreading, my program had a bunch of classes taken directly from minecraft with several slight changes to make it be able to be multithreaded (removing a lot of static modifiers). I'm not sure if it is possible to multithread a program that interfaces directly with minecraft's unmodified code other than launching multiple instances of minecraft itself.

**Comment by Zodsmar** [comment]
How were you pulling the files directly from Minecraft, because that would eliminate me requiring API's etc. If I can make it 100% and lightweight that would be fantastic. Ideally the tool should be able to search Minecraft seeds without even needing Minecraft installed on the computer. This way it can run on servers or in the browser for much faster searching.

**Comment by TelepathicGrunt** [comment]
I simply just made new classes in the program, opened up minecraft's source code with MCP (but this cna be done with forge or fabric now to see source code), and just copied and pasted their code into my program and removed all non-worldgen references until I had a collection of Minecraft's source code for biome/structure gen that is self contained.

**Comment by Zodsmar** [comment]
Damn, that's smart. Since you did that, is your program able to run without Minecraft installed? That would make the software a lot faster and would solve a lot of my problems actually.

**Comment by TelepathicGrunt** [comment]
Yeah it ran without Minecraft needed at all! The code I used was for 1.11 so it's very outdated. If you setup a Fabric workspace, you can see all of Minecraft's source code with somewhat good mappings on.  I think fabric would be better for this as Forge sometimes injects their own mod hooks into the source code which you would've had to find and remove. Here's a tutorial on how to do that: https://fabricmc.net/wiki/tutorial:setup

**Comment by Zodsmar** [comment]
Also if you have discord add me so we can continue this conversation. Zodsmar#0877

**Comment by Zodsmar** [comment]
> Yeah it ran without Minecraft needed at all! The code I used was for 1.11 so it's very outdated. If you setup a Fabric workspace, you can see all of Minecraft's current source code for 1.15.2 with somewhat good mappings on. Or you could even get the new MC snapshots source code too. I think fabric would be better for this as Forge sometimes injects their own mod hooks into the source code which you would've had to find and remove. Here's a tutorial on how to do that: https://fabricmc.net/wiki/tutorial:setup

This is really smart. I'm gonna look into this.

**Comment by KaptainWutax** [comment]
I just found this tool and I browsed the source a little. The biome optimization ideas are great but I find quite uninteresting. The structure search on the other hand has incredible overhead that could easily be avoided. I'm talking at the very least 30 million times faster and that's being generous.

1. Ignoring the horrible amidst overhead problems, there is no need to test every single chunk within a region to see where the structure lands. You only need to run the computation once and see if the coordinates match the input. This should speed it up by around 300 times depending on the structure.

2. It's better to location structures first, then check if biomes match. Biomes are incredibly slow to compute and, as I said, millions of times slower than a good structure search implementation.

3. Structures use the 48 lowest bits while biomes use the full 64 bits. Once you find a matching structure seed you can simply add k * 2^48 where k is in the range [0, 2^16) to get another seed with a different biome map but the same structure layout. You have screwed yourself over by using [nextLong()](https://github.com/Zodsmar/SeedSearcherStandaloneTool/blob/9d216988f5e2d92be76cfa034a67795351b9ee4e/src/main/java/sassa/main/BiomeSearcher.java#L115) though. A side note, not all seeds can come from a nextLong() call, you might wanna figure out a better way to run the search. I digress, using the structure seed approach you can speed up the search by around 2^16 times.

I hope you find this helpful. If you're still maintaining the tool I'd be happy to guide you through it.

**Comment by Zodsmar** [comment]
I am still maintaining it and this is all very useful insight. If you would like to guide me through it or even create a pull request with changes that would be awesome. I would like this tool to be as fast and useful as it can be!

**Comment by Zodsmar** [comment]
With the help of @KaptainWutax and his API's the next version should be much much faster!
