### ISSUE TITLE
Feature Request: Search for specific biomes at specific locations

### ISSUE THREAD

**Issue by Zodsmar** [Zodsmar/SeedSearcherStandaloneTool#43]
From my youtube video:

you should have a feature where it will allow us to search for specific biomes at certain cords. Also be able to do that for multiple biomes so you can really find that perfect biome.

**Comment by MannixTV** [comment]
Something similar to above that I'd love to see added, would be for example set so that 0,0 (or within a set distance from 0,0) has a specific biome and that within a specified range there should be XYZ biomes.

So for example a Mushroom-biome at 0,0 and then within 1000 blocks I'd like there to be at least badlands, desert, jungle, etc. 

Basically having 2 filters, what is to be excluded/included within the different ranges. :D

**Comment by Zodsmar** [comment]
Ideally, I would like to fix this and have it as an option in the tool but for now, the next update will have searching from a predefined list of seeds. So you can search one criteria take those seeds and put it back in to do a second search. Kinda a roundabout way of doing it but it is possible now.

**Comment by Zodsmar** [comment]
To a degree this has been added. You can now search at spawnpoint to get that perfect biome spawn, the take all those seeds that match and pass it back in to get then "n" biome(s) at 1000 blocks out, then if you want to do it again even more check then 2000 blocks out etc. Gonna close this for now but definetely would like to expand on it. If you can add this to the Discussions tab as an Idea so I have track that would great!
